### ISSUE TITLE
could you share the code to prepare the testing datasets?

### ISSUE THREAD

**Issue by fichoo** [xinntao/EDVR#10]
I tried to test my own video pics, however,  memory error always happened.

**Comment by xinntao** [comment]
What is the frame size of your input video?

**Comment by fichoo** [comment]
w 540 
h 960

**Comment by xinntao** [comment]
Is it because out of memory? 
The current model consumes lots of GPU memory if the input frames are too large. 
We will release a relatively smaller model later.
