### ISSUE TITLE
Your EDVR_REDS_deblur_Stage2.pth cannot reproduce the results in your paper

### ISSUE THREAD

**Issue by ysyscool** [xinntao/EDVR#104]
Thanks for your source code and excellent work. I am testing the performance of your pre-trained models. The results of the EDVR_REDS_deblur_L.pth on REDS4 is the same as the paper. While the result of EDVR_REDS_deblur_Stage2.pth is only 25.84 dB not 36.49dB. Can you help me check it? Thanks!

**Comment by xinntao** [comment]
Did you use the outputs of `EDVR_REDS_deblur_L.pth` as the inputs of `EDVR_REDS_deblur_Stage2.pth`?

**Comment by ysyscool** [comment]
> Did you use the outputs of `EDVR_REDS_deblur_L.pth` as the inputs of `EDVR_REDS_deblur_Stage2.pth`?
Thanks! But I come with a new problem. Should the inputs of EDVR_REDS_deblur_Stage2.pth be the flip_test results of EDVR_REDS_deblur_L.pth? I put the outputs of the stage1 model without flip_test as the inputs. The PSNR of the stage2 is 35.71dB.
