### ISSUE TITLE
Maybe REDS's Val Sharp's link failed?

### ISSUE THREAD

**Issue by wlmqjiyizh** [xinntao/EDVR#113]
Hi xinntao.
      Maybe REDS's val_sharp's link failed? The link is still not available even if I use my VPN. 
    "https://cv.snu.ac.kr/~snah/Deblur/dataset/REDS/REDS_validation_set/val_sharp.zip"
    By the way,Ground-truth's other links are valid.
    Looking forward to your reply.

**Comment by DengpanFu** [comment]
Same problem, the link for validation set [val_sharp](https://cv.snu.ac.kr/~snah/Deblur/dataset/REDS/REDS_validation_set/val_sharp.zip) is invalid.@xinntao

**Comment by xinntao** [comment]
If you find the links are invalid, please refer to the official site: https://seungjunnah.github.io/Datasets/reds.html
