### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'io'

### ISSUE THREAD

**Issue by BrainPotter** [xinntao/EDVR#119]
When I run the python train.py -opt options/train/train_SRResNet.yml
I got the following error

export CUDA_VISIBLE_DEVICES=0
Disabled distributed training.
19-11-11 17:11:42.438 - INFO:   name: 001_MSRResNetx4_scratch_DIV2K
  use_tb_logger: True
  model: sr
  distortion: sr
  scale: 4
  gpu_ids: [0]
  datasets:[
    train:[
      name: DIV2K
      mode: LQGT
      dataroot_GT: ../datasets/DIV2K/DIV2K800_sub.lmdb
      dataroot_LQ: ../datasets/DIV2K/DIV2K800_sub_bicLRx4.lmdb
      use_shuffle: True
      n_workers: 6
      batch_size: 16
      GT_size: 128
      use_flip: True
      use_rot: True
      color: RGB
      phase: train
      scale: 4
      data_type: lmdb
    ]
    val:[
      name: val_set5
      mode: LQGT
      dataroot_GT: ../datasets/val_set5/Set5
      dataroot_LQ: ../datasets/val_set5/Set5_bicLRx4
      phase: val
      scale: 4
      data_type: img
    ]
  ]
  network_G:[
    which_model_G: MSRResNet
    in_nc: 3
    out_nc: 3
    nf: 64
    nb: 16
    upscale: 4
    scale: 4
  ]
  path:[
    pretrain_model_G: None
    strict_load: True
    resume_state: None
    root: /home/lijunnian/Desktop/image_Debluring/EDVR
    experiments_root: /home/lijunnian/Desktop/image_Debluring/EDVR/experiments/001_MSRResNetx4_scratch_DIV2K
    models: /home/lijunnian/Desktop/image_Debluring/EDVR/experiments/001_MSRResNetx4_scratch_DIV2K/models
    training_state: /home/lijunnian/Desktop/image_Debluring/EDVR/experiments/001_MSRResNetx4_scratch_DIV2K/training_state
    log: /home/lijunnian/Desktop/image_Debluring/EDVR/experiments/001_MSRResNetx4_scratch_DIV2K
    val_images: /home/lijunnian/Desktop/image_Debluring/EDVR/experiments/001_MSRResNetx4_scratch_DIV2K/val_images
  ]
  train:[
    lr_G: 0.0002
    lr_scheme: CosineAnnealingLR_Restart
    beta1: 0.9
    beta2: 0.99
    niter: 1000000
    warmup_iter: -1
    T_period: [250000, 250000, 250000, 250000]
    restarts: [250000, 500000, 750000]
    restart_weights: [1, 1, 1]
    eta_min: 1e-07
    pixel_criterion: l1
    pixel_weight: 1.0
    manual_seed: 10
    val_freq: 5000.0
  ]
  logger:[
    print_freq: 100
    save_checkpoint_freq: 5000.0
  ]
  is_train: True
  dist: False

/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "train.py", line 310, in <module>
    main()
  File "train.py", line 81, in main
    tb_logger = SummaryWriter(log_dir='../tb_logger/' + opt['name'])
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/tensorboard/writer.py", line 199, in __init__
    self._get_file_writer()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/tensorboard/writer.py", line 248, in _get_file_writer
    self.file_writer = FileWriter(logdir=self.log_dir, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/tensorboard/writer.py", line 65, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/summary/writer/event_file_writer.py", line 73, in __init__
    if not tf.io.gfile.exists(logdir):
  File "/usr/local/lib/python3.5/dist-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'

python 3.5.2
Pytorch 1.0.1
GCC 5.4.0
CUDA 9.0
what should I do to handle the error? thanks in advance.

**Comment by ParanoidPY** [comment]
I meet the same problem and do not know how to solve it. Could you give me some favor?

**Comment by BrainPotter** [comment]
> I meet the same problem and do not know how to solve it. Could you give me some favor?

Try to use pytorch >= 1.1.0 
Best luck!

**Comment by xinntao** [comment]
Also try to use the latest tensorboard by ` pip install tb-nightly future`

**Comment by limingatunc** [comment]
I have encountered the same problem, you just need to update your tensorboard with higher version. Best
