### ISSUE TITLE
How to set align_corners( True or False) when using nn.functional.interpolate? (for example, in EDVR_arch.py, align_corners =False)

### ISSUE THREAD

**Issue by ljmiao** [xinntao/EDVR#133]
in EDVR_arch.py and SRResNet_arch.py, align_corners is set to be False, while in TOF_arch.py, align_corners is set to be True, is there any reason for this?

**Comment by ckkelvinchan** [comment]
For TOFlow, we tested the converted model with both settings and found that **aligned_corners=True** gives a better result. We therefore use **aligned_corners=True** for TOFlow.

**Comment by ljmiao** [comment]
Got it! thanks
