### ISSUE TITLE
Error occurs when "import deform_conv_cuda"

### ISSUE THREAD

**Issue by CVDOU** [xinntao/EDVR#137]
I compile the deform_conv with the guidence, i.e., python setup.py develop. And it generates the file "deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so". 

Error is shown as below.

ImportError: .../deform_conv_cuda.cpython-36m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

**Comment by xinntao** [comment]
You may check this: https://github.com/rbgirshick/py-faster-rcnn/issues/162

**Comment by CVDOU** [comment]
> You may check this: [rbgirshick/py-faster-rcnn#162](https://github.com/rbgirshick/py-faster-rcnn/issues/162)

Thanks.
