### ISSUE TITLE
Question: Why are the results just image files?

### ISSUE THREAD

**Issue by awan-10** [xinntao/EDVR#159]
Thank you for sharing this great work. I have a naïve question about the results. I see that all the files in the results folders are images. Where is the result video? The same question about input video? Or is it just image based input and output and post-processing is done by the users themselves?

**Comment by ckkelvinchan** [comment]
Yes, this code only handles images. You need to manually transform a video into an image sequence and use the image sequence as an input. Similarly, you need to manually transform the output images into a video if you need a video format.

One possible way to do it is to use `ffmpeg`.
