### ISSUE TITLE
Error with Data Preparation

### ISSUE THREAD

**Issue by ChrisMasafu** [xinntao/EDVR#164]
Any help with this guys? I am using my custom dataset;

export CUDA_VISIBLE_DEVICES=0
Path already exists. Rename it to [/home/christophermasafu/EDVR_m/experiments/001_EDVR_OURS_archived_200805-134700]
20-08-05 13:47:00.664 - INFO:   name: 001_EDVR_OURS
  use_tb_logger: True
  model: video_base
  distortion: sr
  scale: 4
  gpu_ids: [0]
  datasets:[
    train:[
      name: REDS
      mode: REDS
      interval_list: [1]
      random_reverse: False
      border_mode: False
      dataroot_GT: ../home/christophermasafu/EDVR_m/datasets/train_GT.lmdb
      dataroot_LQ: ../home/christophermasafu/EDVR_m/datasets/train_LR.lmdb
      cache_keys: meta_info.pkl
      N_frames: 5
      use_shuffle: True
      n_workers: 3
      batch_size: 5
      GT_size: 750
      LQ_size: 750
      use_flip: True
      use_rot: True
      color: RGB
      phase: train
      scale: 4
      data_type: lmdb
    ]
  ]
  network_G:[
    which_model_G: EDVR
    nf: 64
    nframes: 5
    groups: 8
    front_RBs: 5
    back_RBs: 10
    predeblur: False
    HR_in: False
    w_TSA: False
    scale: 4
  ]
  path:[
    pretrain_model_G: None
    strict_load: True
    resume_state: None
    root: /home/christophermasafu/EDVR_m
    experiments_root: /home/christophermasafu/EDVR_m/experiments/001_EDVR_OURS
    models: /home/christophermasafu/EDVR_m/experiments/001_EDVR_OURS/models
    training_state: /home/christophermasafu/EDVR_m/experiments/001_EDVR_OURS/training_state
    log: /home/christophermasafu/EDVR_m/experiments/001_EDVR_OURS
    val_images: /home/christophermasafu/EDVR_m/experiments/001_EDVR_OURS/val_images
  ]
  train:[
    lr_G: 0.0004
    lr_scheme: CosineAnnealingLR_Restart
    beta1: 0.9
    beta2: 0.99
    niter: 600000
    warmup_iter: -1
    T_period: [150000, 150000, 150000, 150000]
    restarts: [150000, 300000, 450000]
    restart_weights: [1, 1, 1]
    eta_min: 1e-07
    pixel_criterion: cb
    pixel_weight: 1.0
    val_freq: 5000.0
    manual_seed: 0
  ]
  logger:[
    print_freq: 100
    save_checkpoint_freq: 5000.0
  ]
  is_train: True
  dist: True

20-08-05 13:47:00.739 - INFO: Random seed: 0
20-08-05 13:47:00.740 - INFO: Temporal augmentation interval list: [1], with random reverse is False.
20-08-05 13:47:00.740 - INFO: Using cache keys: meta_info.pkl
20-08-05 13:47:00.740 - INFO: Using cache keys - meta_info.pkl.
Traceback (most recent call last):
  File "/home/christophermasafu/EDVR_m/codes/train.py", line 310, in <module>
    main()
  File "/home/christophermasafu/EDVR_m/codes/train.py", line 104, in main
    train_set = create_dataset(dataset_opt)
  File "/home/christophermasafu/EDVR_m/codes/data/__init__.py", line 44, in create_dataset
    dataset = D(dataset_opt)
  File "/home/christophermasafu/EDVR_m/codes/data/REDS_dataset.py", line 53, in __init__
    self.paths_GT = pickle.load(open('./data/{}'.format(cache_keys), 'rb'))["keys"]
FileNotFoundError: [Errno 2] No such file or directory: './data/meta_info.pkl'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/christophermasafu/venv/lib/python3.8/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/christophermasafu/venv/lib/python3.8/site-packages/torch/distributed/launch.py", line 258, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/christophermasafu/venv/bin/python3', '-u', '/home/christophermasafu/EDVR_m/codes/train.py', '--local_rank=0', '-opt', '/home/christophermasafu/EDVR_m/codes/options/train/train_EDVR_OURS_M.yml', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by xinntao** [comment]
REDS dataset use  './data/meta_info.pkl' to store meta information. But your custom dataset may not have such meta info. For your own custom dataset, you may need to write a new dataset to fulfil your needs. 

BTW, we have updated the codes, you may try to use the new codes :-)

**Comment by ChrisMasafu** [comment]
> REDS dataset use './data/meta_info.pkl' to store meta information. But your custom dataset may not have such meta info. For your own custom dataset, you may need to write a new dataset to fulfil your needs.
> 
> BTW, we have updated the codes, you may try to use the new codes :-)

Thank you!
