### ISSUE TITLE
想咨询论文中关于PCD的溶解实验

### ISSUE THREAD

**Issue by RyanXingQL** [xinntao/EDVR#168]
您好！EDVR文中对PCD的溶解实验有这么一幅图：

![image](https://user-images.githubusercontent.com/34084019/90713132-3dbf1380-e2d7-11ea-9d97-58d95fe92ac6.png)

而PCD是对feature进行的alignment，而不是对frame进行alignment。请问28和30帧的灰度图又是如何得到的呢？

感谢您的解答，祝您工作顺利！

**Comment by xinntao** [comment]
1. 灰度图。当我们得到warped features后，灰度图只是visualization。选择一个通道， 将其归一化到[0， 1], 然后当作图片来visualization即可。
2. Feature的光流。同理，我们选取feature的一个通道, 将其归一化到[0， 1], 当作图像输入到flow net, 可以得到光流。

**Comment by wenchen4321** [comment]
Hello, How did you get Flow Magnitude from the optical flow map?
