### ISSUE TITLE
 _ZN2at19UndefinedTensorImpl10_singletonE

### ISSUE THREAD

**Issue by 205418367** [xinntao/EDVR#17]
hi, I use ubuntu18.04; python 3.6; pytorch 1.1.0. when  i run `python3 test_Vid4_REDS4_with_GT.py`, i meet a  follow error:

ImportError: /home/lichen/EDVR/codes/models/modules/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

what can i do?

**Comment by kenrubiooo** [comment]
Hi! How did you solve this one?

**Comment by hufengshuo07** [comment]
@205418367 Have you solved the problem and how ,Thanks??

**Comment by xiaozhi2015** [comment]
Delete _ext.cpython-36m-x86_64-linux-gnu.so and build dir, then redo sh make.sh

**Comment by DunguTmp** [comment]
> Delete _ext.cpython-36m-x86_64-linux-gnu.so and build dir, then redo sh make.sh

Hi! I want to know what's you mean of build dir. Can U tell me about this command?
First, I rm -rf this _ext.cpython.xxx file,
Then I redo sh make.sh.
But this issue has not been solved.

**Comment by xiaozhi2015** [comment]
Delete “_ext.cpython-36m-x86_64-linux-gnu.so and build“, install pytorch by source code, or update your gcc to version 4.9. Since pytorch 1.1 was built with gcc 4.9 when install by pip.
