### ISSUE TITLE
An error occurred while running the test code

### ISSUE THREAD

**Issue by wxy1234567** [xinntao/EDVR#32]
An error occurred while running the test code:
19-06-12 21:59:26.515 - INFO: Data: Vid4 - ../datasets/Vid4/BIx4/*
19-06-12 21:59:26.515 - INFO: Padding mode: new_info
19-06-12 21:59:26.515 - INFO: Model path: ../experiments/pretrained_models/EDVR_Vimeo90K_SR_L.pth
19-06-12 21:59:26.515 - INFO: Save images: True
19-06-12 21:59:26.515 - INFO: Flip Test: False
error in modulated_deformable_im2col_cuda: CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
   ......
  File "/home/wxy//EDVR/codes/models/modules/DCNv2/dcn_v2.py", line 135, in forward
    if offset_mean > 100:
RuntimeError: CUDA error: an illegal memory access was encountered

The error prompted me that my CUDA did not match the driver version, but it turned out that my CUDA was working properly.
My pytorch version is 1.0.1，CUDA version is 9.0,And Make.sh has run successfully.Look forward to your reply！

**Comment by xinntao** [comment]
Check whether your CUDA driver is sufficient for your CUDA version. 
[Table 1](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html)

**Comment by wxy1234567** [comment]
Thank you for your reply. It's settled, but CUDA is available in other projects.
