### ISSUE TITLE
about REDS_dataset.py

### ISSUE THREAD

**Issue by lcd111** [xinntao/EDVR#33]
我不太理解这个py文件里 大概在140行左右   neighbor_list 的取值 如果  center_frame_idx是0/1/98/99的话  这个neighbor_list会出现负数或者大于99

**Comment by hahahaprince** [comment]
The URL of this competitions is 404. Can anyone share the download link of REDS dataset. Thank you! @lcd111

**Comment by xinntao** [comment]
@hahahaprince 
You can find the REDS dataset download links: https://github.com/xinntao/EDVR/wiki/Prepare-datasets-in-LMDB-format

OR 

https://seungjunnah.github.io/Datasets/reds
