### ISSUE TITLE
Another problem in VSR

### ISSUE THREAD

**Issue by splinter21** [xinntao/EDVR#35]
How about subtitle region ？
There is no motion in subtitle region, but it changes instantaneous between two frames.
Example figure(Average between 5 frames. The head region can be aligned, but the subtitle region can't be aligned.):
![avg](https://user-images.githubusercontent.com/26759495/59547757-89a95680-8f76-11e9-8644-66508db653eb.png)

Now we can't label the subtitle region, but the model should be robust for these kind of situations.(Another situation is for anime videos(2D painting). Just use SISR methods for SR.)
Will it influence the training when there is subtitle region included in the input patches of network?

This problem is caused by the diffenrence between experimental environment in academic research and practical application. In ideal experimental datasets, subtitle is not included.

**Comment by splinter21** [comment]
Now we can't label the subtitle region, but the model should be robust for these kind of situations.
Will it influence the training when there is subtitle region included in the input patches of network?

**Comment by splinter21** [comment]
Maybe I can calculate the optical flow between center frames to get six maps, and use these six maps to kill the subtitle region and static region in neibor frames（these are the preprocess）.
What's your opinion? Will this be helpful to learn more motion details from neighbor frames?

**Comment by xinntao** [comment]
I think using SISR for subtitle is more appropriate because there is little information from other frames in the subtitle region. Is it possible to use some simple tricks to detect the subtitle regions and then process these regions separately?
