### ISSUE TITLE
Error on Vid4 dataset

### ISSUE THREAD

**Issue by surfingnirvana** [xinntao/EDVR#5]
This error occurs with the testing codes:

19-05-28 13:52:03.735 - INFO: Data: Vid4 - ../datasets/Vid4/BIx4/*
19-05-28 13:52:03.736 - INFO: Padding mode: new_info
19-05-28 13:52:03.736 - INFO: Model path: ../experiments/pretrained_models/EDVR_Vimeo90K_SR_L.pth
19-05-28 13:52:03.736 - INFO: Save images: True
19-05-28 13:52:03.736 - INFO: Flip Test: False
Traceback (most recent call last):
  File "test_Vid4_REDS4_with_GT.py", line 275, in <module>
    main()
  File "test_Vid4_REDS4_with_GT.py", line 228, in main
    crt_psnr = util.calculate_psnr(cropped_output * 255, cropped_GT * 255)
 EDVR-master\codes\utils\util.py", line 138, in calculate_psnr
    mse = np.mean((img1 - img2)**2)
ValueError: operands could not be broadcast together with shapes (576,720) (144,180)

**Comment by xinntao** [comment]
Did you use windows? It works on my computer with Ubuntu.

Form your error `EDVR-master\codes\utils\util.py` , you can try 
change `sub_folder_GT = sub_folder.replace('/BIx4/', '/GT/')` to `sub_folder_GT = sub_folder.replace('BIx4', 'GT')`

**Comment by surfingnirvana** [comment]
Yes Windows 10. That did the trick it is working. I also changed sub_folder_GT = sub_folder.replace('/{}/'.format(data_mode), '/GT/') to sub_folder_GT = sub_folder.replace('{}'.format(data_mode), 'GT')
Thank you.

**Comment by surfingnirvana** [comment]
Are the models (EDVR_REDS_deblurcomp_L.pth) specifically trained for the 1280x720 resolution? Or is there anyway to modify the input resolution? Thank you.

**Comment by xinntao** [comment]
This model is trained for REDS. You can test inputs with other resolution but the performance may drop.
