### ISSUE TITLE
Availability of output frames for REDS4 clips

### ISSUE THREAD

**Issue by TouqeerAhmad** [xinntao/EDVR#54]
Hi Xintao, 

Would you be able to share the output frames generated by EDVR for REDS4 clips for video deblurring problem. That shall be very helpful, since, you already have them and it can save me some time instead or running the inference. 

Thanks,
Touqeer

**Comment by xinntao** [comment]
You can download them from [Model-Zoo](https://github.com/xinntao/EDVR/wiki/Model-Zoo)

**Comment by TouqeerAhmad** [comment]
Thanks!
