### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by satsukiyatoshi** [xinntao/EDVR#56]
Hello
I'm trying to use the test_Vid4_REDS4_with_GT.py script with a foder containing 98 png files (named from 00000001.png to 00000099.png).
The png resolution is 320*240.

when i use the script i got this error:
```
  File "test_Vid4_REDS4_with_GT.py", line 276, in <module>
    main()
  File "test_Vid4_REDS4_with_GT.py", line 217, in main
    GT = np.copy(img_GT_l[img_idx])
IndexError: list index out of range
```
And when i look at result i can see it have processed the first png file but not the others

Thanks for helping ^^

**Comment by siyux** [comment]
You can print the "img_idx" which can't be processed, and make sure if the image exists.

**Comment by satsukiyatoshi** [comment]
Thanks, i get it works by setting up the folders in a static way in the script
