### ISSUE TITLE
An error occurred in bash make.sh

### ISSUE THREAD

**Issue by kevin-collins** [xinntao/EDVR#58]
dcn_v2_cuda.obj : error LNK2001: ▒޷▒▒▒▒▒▒▒▒ⲿ▒▒▒▒ "struct THCState * state" (?state@@3PEAUTHCState@@EA)
build\lib.win-amd64-3.6\_ext.cp36-win_amd64.pyd : fatal error LNK1120: 1 ▒▒▒޷▒▒▒▒▒▒▒▒ⲿ▒▒▒▒
C:\Users\Kevin Collins\AppData\Roaming\Python\Python36\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
error: command 'E:\\vs\\VC\\Tools\\MSVC\\14.11.25503\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120

**Comment by siyux** [comment]
You'd better use GCC version 5.4.0 and recompile it.

**Comment by kevin-collins** [comment]
Referring to this website https://github.com/xingyizhou/CenterNet/issues/7，I have solved this problem

**Comment by yuanjunchai** [comment]
GCC version 7.3.0, cuda 8.0 
And there is error:
error -- unsupported GNU version! gcc versions later than 5 are not supported!
  ^~~~~
error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1

**Comment by matt-teng** [comment]
How did you solve this problem? I have met the same problem.
