### ISSUE TITLE
some error in bash make.sh

### ISSUE THREAD

**Issue by yanmenglu** [xinntao/EDVR#6]
![image](https://user-images.githubusercontent.com/23131833/58479632-391ab680-818b-11e9-8881-b4edd7d6216b.png)

**Comment by xinntao** [comment]
Which pytorch version do you use?

**Comment by yanmenglu** [comment]
I use anaconda, pytorch==1.0.1

**Comment by yanmenglu** [comment]
is that because of pytorch version?

**Comment by xinntao** [comment]
Emmm... Pytorch1.0.1 should be OK. You may google it for the solution.

**Comment by yanmenglu** [comment]
yes, thank you .

**Comment by WWYFAITH** [comment]
I have encountered the same problem, but I still don't know how to solve it.

**Comment by xinntao** [comment]
@WWYFAITH I haven't encountered this problem. You may go to the [DCNv2 issue page](https://github.com/CharlesShang/DCNv2/issues) to find whether there is any solution.
