### ISSUE TITLE
Is weight norm better than no batch norm, no batch norm better than batch norm?

### ISSUE THREAD

**Issue by robotzheng** [xinntao/EDVR#65]
I try weight_norm, but can not avoid the "more than 100" error.

**Comment by xinntao** [comment]
I have not tried weight norm. 
No batch norm is better than batch norm. 

If you train EDVR-M, it is not very likely to encounter this warning. Did you always meet this warning?

**Comment by robotzheng** [comment]
yes, I want to train a big model with options: RB40 frames23.
