### ISSUE TITLE
Missing key(s) in state_dict: "tsa_fusion.tAtt_1.weight"

### ISSUE THREAD

**Issue by robotzheng** [xinntao/EDVR#71]
train a model with tsa=true from a pretrained model with tsa=false .

RuntimeError: Error(s) in loading state_dict for EDVR:
	Missing key(s) in state_dict: "tsa_fusion.tAtt_1.weight", "tsa_fusion.tAtt_1.bias", "tsa_fusion.tAtt_2.weight", "tsa_fusion.tAtt_2.bias", "tsa_fusion.fea_fusion.weight", "tsa_fusion.fea_fusion.bias", "tsa_fusion.sAtt_1.weight", "tsa_fusion.sAtt_1.bias", "tsa_fusion.sAtt_2.weight", "tsa_fusion.sAtt_2.bias", "tsa_fusion.sAtt_3.weight", "tsa_fusion.sAtt_3.bias", "tsa_fusion.sAtt_4.weight", "tsa_fusion.sAtt_4.bias", "tsa_fusion.sAtt_5.weight", "tsa_fusion.sAtt_5.bias", "tsa_fusion.sAtt_L1.weight", "tsa_fusion.sAtt_L1.bias", "tsa_fusion.sAtt_L2.weight", "tsa_fusion.sAtt_L2.bias", "tsa_fusion.sAtt_L3.weight", "tsa_fusion.sAtt_L3.bias", "tsa_fusion.sAtt_add_1.weight", "tsa_fusion.sAtt_add_1.bias", "tsa_fusion.sAtt_add_2.weight", "tsa_fusion.sAtt_add_2.bias". 
	Unexpected key(s) in state_dict: "tsa_fusion.weight", "tsa_fusion.bias".

**Comment by xinntao** [comment]
A model with tsa=true has more weights. You can set `strict_load: false`, which only loads the existing weights.

**Comment by robotzheng** [comment]
thanks.
