### ISSUE TITLE
The URL of this competitions is 404.  Can anyone share the download link of REDS dataset. Thank you!

### ISSUE THREAD

**Issue by hahahaprince** [xinntao/EDVR#77]
The URL of this competitions is 404.  https://competitions.codalab.org/competitions/21476
Can anyone share the download link of REDS dataset. Thank you!

**Comment by xinntao** [comment]
https://github.com/xinntao/EDVR/wiki/Prepare-datasets-in-LMDB-format

OR 

https://seungjunnah.github.io/Datasets/reds

**Comment by hahahaprince** [comment]
OK !
