### ISSUE TITLE
About the request of “EDVR_REDS_deblur_Stage2.pth”

### ISSUE THREAD

**Issue by ZYzhouya** [xinntao/EDVR#79]
Dear authors,
Could you supplement the pretrained model “EDVR_REDS_deblur_Stage2.pth” in Model Zoo?
I am really curious about the improvement compared with only stage 1.
Thanks!!!

**Comment by xinntao** [comment]
You can find them in https://github.com/xinntao/EDVR/wiki/Model-Zoo

**Comment by ZYzhouya** [comment]
> You can find them in https://github.com/xinntao/EDVR/wiki/Model-Zoo

Thanks for your reply!
