### ISSUE TITLE
Mixed Precision Training (Apex)

### ISSUE THREAD

**Issue by TouqeerAhmad** [xinntao/EDVR#98]
Hi, have anybody looked into training EDVR using Apex API -- I have been trying but getting issues due to DCNv2. Wanted to know if anyone else has tried or have some wisdom to share.

**Comment by xinntao** [comment]
Thanks @TouqeerAhmad 
We now use [the mmdection](https://github.com/open-mmlab/mmdetection)'s dcn implementation. mmdetection supports fp16 training. Maybe there is a solution in mmdection.

**Comment by Hshihua** [comment]
@TouqeerAhmad Have you found any solution to this issue?
